"""
Cues for the Fall Rally spot.

The rally is not a car, so it does not come out of make_cues.py: there is no
listing, no 4-hour rate, and the plate is a montage of six cars rather than one
car's reel. Everything on screen is read off supercarexp.vip/rally and lives in
sce_brand.RALLY.

    python3 make_rally_cues.py
    python3 build_ad.py --car fall-rally --all

The plate is built by make_montage.py, not make_plate.py. See PLATES.md.
"""
import json, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "99-toolkit"))
import sce_brand as B                                    # noqa: E402
from make_cues import beats                              # noqa: E402

SLUG = "fall-rally"
T = 18.0                     # six 3s cuts
R = B.RALLY
PRICE = f"${R['price']:,}"
OFF = f"${R['off']:,}"

TITLE = f"{R['name']} {R['year']}"
SRC = ("Dates, route, price, code, inclusions and the tagline are all from "
       "supercarexp.vip/rally. Phone from the site footer.")

VARIANTS = [
    dict(variant="a-price", cta="booking_book-now",
         angle="Price. One number and one date, for someone already deciding.",
         hook=[f"{PRICE}.", "PER CAR."], build=R["dates"],
         heading="THE RALLY",
         rows=[["01", "NOV 13-16", R["year"]],
               ["02", PRICE, R["unit"]],
               ["03", R["code"], f"{OFF} OFF"],
               ["04", "3 CITIES", "VEGAS · SD · SB"]]),
    dict(variant="b-experience", cta="booking_reserve-your-ride",
         angle="What the ticket actually covers. The objection is 'what am I paying for'.",
         hook=["THREE ICONIC", "DESTINATIONS."], build=TITLE,
         heading="WHAT YOU GET",
         rows=[["01", "HOTELS", "EVERY NIGHT"],
               ["02", "CO-PILOT", "NO EXTRA COST"],
               ["03", "SUPPORT", "CHECKPOINTS · CARS"],
               ["04", "SWAG", "DECALS · AWARDS"]]),
    dict(variant="c-occasion", cta="quote_dm-for-dates",
         angle="The route. A rally sells the drive, not the car.",
         hook=["NOV 13-16.", "VEGAS TO THE COAST."], build="FOUR STARTS, ONE ROUTE",
         heading="THE ROUTE",
         rows=[["01", "DAY 1", "LAS VEGAS · NOV 13"],
               ["02", "DAY 2", "SAN DIEGO · NOV 14"],
               ["03", "DAY 3", "SANTA BARBARA · NOV 15"],
               ["04", "DAY 4", "LAS VEGAS · NOV 16"]]),
    dict(variant="d-offer", cta="booking_book-now",
         angle="The code. The only variant with a reason to act today.",
         hook=[f"{OFF} OFF.", f"CODE {R['code']}."], build=R["spots"],
         heading="THE OFFER",
         rows=[["01", R["code"], "THE CODE"],
               ["02", f"{OFF} OFF", R["unit"]],
               ["03", PRICE, "ENTRY"],
               ["04", "CALL", B.PHONE]]),
    dict(variant="e-engage", cta="engagement_tag-your-copilot",
         angle="A question, not an ask. The co-pilot seat is free, so the tag is the point.",
         hook=["WHO IS YOUR", "CO-PILOT?"], build="CO-PILOT INCLUDED",
         heading="THE RALLY",
         rows=[["01", "CO-PILOT", "INCLUDED"],
               ["02", "NOV 13-16", R["year"]],
               ["03", PRICE, R["unit"]],
               ["04", "SPOTS", "LIMITED"]]),
]


def make(v):
    cta = f"cta-captions/cta_9x16_{v['cta']}_bar.png"
    assert (B.OVERLAYS / cta).exists(), cta
    return {
        "_comment": f"Supercar Experience Fall Rally - variant {v['variant']}. "
                    "Generated by make_rally_cues.py; edit the table there.",
        "_source": SRC,
        "slug": SLUG,
        "canvas": "9x16", "width": 1080, "height": 1920, "fps": 30, "duration": T,
        "plate": "source/plate-1080x1920.mp4",
        "_plate_note": "Montage of six cars, 3s each, built by make_montage.py.",
        "car": TITLE, "build": v["build"],
        "ticker": [B.BRAND_NAME, R["name"], R["dates"]],
        "hook": v["hook"],
        "buildHeading": v["heading"], "buildRows": v["rows"],
        "_buildRows_note": "Every line is on supercarexp.vip/rally. No invented figures.",
        "ctaOverlay": cta, "endCard": "end-cards/endcard_9x16_dark.png",
        "beats": beats(T),
        "layout": {"marginLeftFrac": 0.075, "marginRightFrac": 0.16, "bandTopFrac": 0.40},
        "layoutStyle": "panel",
        "_layoutStyle_note": "From source/zones.json: the mid band swings 47-178 across "
                             "the cuts, so the copy sits on a card.",
        "grade": "eq=contrast=1.04:saturation=0.96:gamma=1.0,vignette=angle=PI/5",
        "variant": v["variant"], "variantAngle": v["angle"],
    }


def main():
    d = HERE / SLUG / "variants"
    d.mkdir(parents=True, exist_ok=True)
    for v in VARIANTS:
        (d / f"cue-{v['variant']}.json").write_text(
            json.dumps(make(v), indent=2, ensure_ascii=False) + "\n")
    (HERE / SLUG / "cue.json").write_text(
        json.dumps(make(VARIANTS[0]), indent=2, ensure_ascii=False) + "\n")
    print(len(VARIANTS), "rally cues + base cue")


if __name__ == "__main__":
    main()
