#!/usr/bin/env python3
"""
Formula Dynamics Performance - asset index.

Walks the kit and writes ASSET-INDEX.md so the listing can never drift from
what is actually on disk.

Run:  python3 99-toolkit/build_index.py
"""

import fd_brand as B

SKIP_DIRS = {"99-toolkit", ".git"}

BLURB = {
    "01-brand-core": "The rules: brand spec, tokens, master guide, colour swatches.",
    "01-brand-core/color-swatches": "Solid 1080x1080 colour fills. Drag in as a background.",
    "02-logos": "Logo lockups.",
    "02-logos/svg-vector": "True vector. Use anywhere that accepts SVG.",
    "02-logos/png-transparent": "Transparent PNG at 1000 / 2000 / 4000 px wide. Use in CapCut.",
    "02-logos/png-on-black": "Flat black background, for when transparency misbehaves.",
    "02-logos/png-on-white": "Flat white background.",
    "03-overlays": "Drop-on-timeline video graphics.",
    "03-overlays/corner-logo-bugs": "Logo pre-positioned on a full-size transparent frame. No scaling needed.",
    "03-overlays/lower-thirds": "Service, partner and CTA name plates.",
    "03-overlays/title-cards": "Two-line opening titles.",
    "03-overlays/end-cards": "Full-frame closing cards with contact details.",
    "03-overlays/service-badges": "Chips for feature callouts.",
    "03-overlays/accent-bars": "Racing stripe and solid red bars. Also good as transitions.",
    "03-overlays/partner-logos": "Empty - drop official partner assets here.",
    "04-templates": "Reference material.",
    "04-templates/safe-zone-guides": "Platform keep-out overlays. Hide before export.",
    "04-templates/reference-posters": "The campaign posters, for art direction reference.",
    "05-copy-library": "Hooks, captions, hashtags, voice, service and partner wording.",
    "06-video-system": "How to shoot, edit and export.",
    "07-fonts": "Bebas Neue plus notes on the accent face.",
    "08-download-bundles": "Zipped packs ready to download and unzip. Start with the vertical starter pack.",
}


def main():
    lines = [
        "# Asset Index",
        "",
        "Generated by `99-toolkit/build_index.py` - do not edit by hand.",
        "",
        "File counts and names are read straight off disk, so this always",
        "matches reality. Re-run after adding anything.",
        "",
    ]

    total = 0
    for d in sorted(p for p in B.KIT.rglob("*") if p.is_dir()):
        rel = d.relative_to(B.KIT).as_posix()
        if any(rel == s or rel.startswith(s + "/") for s in SKIP_DIRS):
            continue

        files = sorted(f for f in d.iterdir() if f.is_file() and f.name != ".gitkeep")
        total += len(files)

        lines.append(f"## `{rel}/`")
        note = BLURB.get(rel)
        if note:
            lines.append("")
            lines.append(note)
        lines.append("")

        if not files:
            lines += ["*(empty)*", ""]
            continue

        # Long, systematic sets are summarised by pattern rather than listed
        # one by one - a 64-row table of near-identical filenames helps nobody.
        if len(files) > 14:
            size = sum(f.stat().st_size for f in files)
            lines.append(f"**{len(files)} files** ({size / 1_048_576:.1f} MB). Examples:")
            lines.append("")
            for f in files[:5]:
                lines.append(f"- `{f.name}`")
            lines.append(f"- …and {len(files) - 5} more following the same pattern")
            lines.append("")
        else:
            lines.append("| File | Size |")
            lines.append("|---|---|")
            for f in files:
                kb = f.stat().st_size / 1024
                size = f"{kb / 1024:.1f} MB" if kb > 1024 else f"{kb:.0f} KB"
                lines.append(f"| `{f.name}` | {size} |")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"**{total} files total.**")
    lines.append("")

    (B.KIT / "ASSET-INDEX.md").write_text("\n".join(lines))
    return total


if __name__ == "__main__":
    print(f"Indexed {main()} files -> ASSET-INDEX.md")
