#!/usr/bin/env python3
"""
Formula Dynamics Performance - machine-readable brand tokens.

Emits 01-brand-core/brand-tokens.json and brand-tokens.css from fd_brand.py so
the written spec and any code that consumes it can never drift apart.

Run:  python3 99-toolkit/build_tokens.py
"""

import json

import fd_brand as B


def build():
    tokens = {
        "brand": {
            "name": "Formula Dynamics Performance",
            "website": B.WEBSITE,
            "instagram": B.INSTAGRAM,
            "email": B.EMAIL,
        },
        "color": {name: {"hex": hex_code, "rgb": list(B.rgb(hex_code)), "role": role}
                  for name, hex_code, role in B.PALETTE},
        "accentStripe": [{"color": c, "share": s} for c, s in B.ACCENT_STRIPE],
        "type": {
            "primary": {"family": B.TYPE_PRIMARY, "use": "headlines",
                        "license": "SIL OFL 1.1", "bundled": True},
            "accent": {"family": B.TYPE_ACCENT, "use": "performance / accent",
                       "license": "commercial", "bundled": False},
        },
        "logo": {
            "clearSpace": "one FD icon height on all sides",
            "minWidthPx": 120,
            "minWidthPrintMm": 25,
        },
        "canvas": {k: {"width": w, "height": h} for k, (w, h) in B.CANVASES.items()},
        "safeZones": {"9x16": B.SAFE_ZONES_9X16},
        "services": [{"slug": s, "label": l, "description": d,
                      "subline": B.SERVICE_SUBLINE[s]} for s, l, d in B.SERVICES],
        "priorityServices": B.PRIORITY_SERVICES,
        "partners": [{"slug": s, "label": l, "name": n, "category": c}
                     for s, l, n, c in B.PARTNERS],
    }

    (B.BRAND_CORE / "brand-tokens.json").write_text(
        json.dumps(tokens, indent=2) + "\n")

    lines = [
        "/* Formula Dynamics Performance - brand tokens",
        "   Generated by 99-toolkit/build_tokens.py - do not edit by hand. */",
        "",
        ":root {",
    ]
    for name, hex_code, role in B.PALETTE:
        lines.append(f"  --fd-{name}: {hex_code};              /* {role} */")
    lines += [
        "",
        f'  --fd-font-primary: "{B.TYPE_PRIMARY}", "Oswald", '
        '"Arial Narrow", sans-serif;',
        f'  --fd-font-accent: "{B.TYPE_ACCENT}", "{B.TYPE_PRIMARY}", sans-serif;',
        "",
        "  --fd-logo-min-width: 120px;",
        "}",
        "",
        "/* Four-colour racing stripe */",
        ".fd-accent-stripe {",
        "  background: linear-gradient(to right,",
    ]
    pos = 0.0
    stops = []
    for hex_code, share in B.ACCENT_STRIPE:
        stops.append(f"    {hex_code} {pos * 100:.0f}% {(pos + share) * 100:.0f}%")
        pos += share
    lines.append(",\n".join(stops))
    lines += ["  );", "  height: 6px;", "}", ""]

    (B.BRAND_CORE / "brand-tokens.css").write_text("\n".join(lines))
    return 2


if __name__ == "__main__":
    print(f"Wrote {build()} token files to 01-brand-core/.")
