#!/usr/bin/env python3
"""
Supercar Experience - overlays for long-form and vlog footage.

The base kit (build_overlays) and the rental kit (build_rental) are both
ad-shaped: they name a car, quote a price and ask for the booking. A vlog
needs different furniture. It runs for minutes rather than fifteen seconds,
it has someone talking to camera, it moves through segments, and it is shot
somewhere on a day.

Four pieces, none of which the ad kit can stand in for:

    name      who is on camera. The ad kit's lower thirds name cars and
              locations; there is no way to name a person.
    chapter   a neutral segment marker. The ad kit's title cards all carry
              campaign copy - "BOOK THE WEEKEND" - so they cannot mark
              "02 / WALKAROUND".
    stamp     small corner place-and-date, the documentary convention.
    music     track credit, needed now the cuts carry licensed music.
    follow    a persistent corner nudge pointing at the site.

Text that is fixed (the three locations, the follow bug) is pre-generated by
build(). Text that changes per video (a name, a chapter, a track) is a
command, because pre-rendering a guess would just be a file to delete:

    python3 build_vlog.py name    --name "OMARIE" --role "HOST"
    python3 build_vlog.py chapter --index 02 --label "WALKAROUND"
    python3 build_vlog.py stamp   --place "SCOTTSDALE" --sub "ARIZONA" \\
                                  --date "12 SEP 2026"
    python3 build_vlog.py music   --track "RUN RUN RUN" --artist "DUTCH MELROSE"
    python3 build_vlog.py all

Per the brief, nothing here names a social handle - the site is the only
address on screen, so the overlays do not go stale if an account changes.
"""
import argparse
import re

from PIL import Image, ImageDraw

import sce_brand as B
import fd_render as R
import build_overlays as O

OUT = B.OVERLAYS / "vlog"
GREY = "#C9C9D0"
CANVASES = ("16x9", "9x16", "4x5", "1x1")


def _slug(s):
    """A filename-safe token, so --label "The Drive" lands as the-drive."""
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-") or "untitled"


def _corner(canvas, corner):
    """Anchor point for a corner piece, honouring the platform keep-out zones.

    Vertical video is the one that bites: TikTok and Reels put the like /
    comment / share rail down the RIGHT side, which SAFE_ZONES_9X16 records as
    16% of the width, and the caption across the bottom 20%. A piece placed at
    a flat 5% inset sits underneath the action buttons - it renders fine and is
    invisible in the app. Wider canvases have no such furniture.
    """
    fw, fh = B.CANVASES[canvas]
    if canvas == "9x16":
        z = B.SAFE_ZONES_9X16
        left, right, top, bottom = z["left"], z["right"], z["top"], z["bottom"]
    else:
        left = right = 0.05
        top = bottom = 0.08
    x = round(fw * left) if corner.endswith("left") else fw - round(fw * right)
    y = round(fh * top) if corner.startswith("top") else fh - round(fh * bottom)
    anchor = ("l" if corner.endswith("left") else "r") + \
             ("t" if corner.startswith("top") else "b")
    return x, y, anchor


# ==========================================================================
# 1. Name bar - who is on camera
# ==========================================================================
def name_bar(canvas, name, role=None):
    """The kit's own lower third, given a person instead of a car.

    Deliberately not a new design. A vlog cuts between the host and the car,
    and if the two name plates differ the edit looks like two brands. Same
    panel, same gold bar, same stripe - only the content changes.
    """
    return O.lower_third(canvas, name.upper(),
                         role.upper() if role else None,
                         B.BRAND_NAME)


# ==========================================================================
# 2. Chapter marker
# ==========================================================================
def chapter(canvas, index, label, tone="dark"):
    """Numeral, hairline, word - the segment marker.

    No panel. A chapter card is on screen for a beat and then gone, so it can
    carry the typographic treatment the spec run uses: the numeral is the
    graphic and the only furniture is a rule. A soft scrim underneath keeps it
    legible when the cut lands on sky.
    """
    fw, fh = B.CANVASES[canvas]
    im = R.frame(canvas)
    scale = fw / 1080.0
    ink = B.WHITE if tone == "dark" else B.BLACK

    if tone == "dark":
        R.paste(im, O.title_scrim(canvas, top=0.34, height=0.30, strength=150), 0, 0)

    num_im = R.text(str(index), round(190 * scale), B.GOLD, tracking=0.02)
    lab_im = R.fit_text(label.upper(), min(round(fw * 0.62), round(fw * 0.62)),
                        max_height=round(96 * scale), color=ink, tracking=0.06)

    left = round(fw * 0.08)
    mid = round(fh * 0.50)
    R.paste(im, num_im, left, mid, anchor="lm")

    rule_x = left + num_im.width + round(34 * scale)
    rule_h = max(num_im.height, lab_im.height) + round(16 * scale)
    d = ImageDraw.Draw(im)
    d.rectangle([rule_x, mid - rule_h // 2, rule_x + max(2, round(3 * scale)),
                 mid + rule_h // 2], fill=B.rgb(ink) + (230,))

    R.paste(im, lab_im, rule_x + round(34 * scale), mid, anchor="lm")
    R.paste(im, R.accent_stripe(round(fw * 0.22), round(9 * scale)),
            left, mid + rule_h // 2 + round(30 * scale))
    return im


# ==========================================================================
# 3. Place-and-date stamp
# ==========================================================================
def stamp(canvas, place, sub=None, date=None, corner="top-left", tone="dark"):
    """Small documentary stamp: a gold hairline and two short lines.

    Sized to sit in a corner for the whole shot, so it is kept well under the
    lower third's weight - it should read as a caption on the footage, not as
    a second name plate competing with the first.
    """
    fw, fh = B.CANVASES[canvas]
    im = R.frame(canvas)
    scale = fw / 1080.0
    ink = B.WHITE if tone == "dark" else B.BLACK
    sub_ink = GREY if tone == "dark" else "#4A4A52"

    place_im = R.text(place.upper(), round(44 * scale), ink, tracking=0.10)
    lines = [l for l in (sub, date) if l]
    sub_ims = [R.text(l.upper(), round(26 * scale), sub_ink, tracking=0.16) for l in lines]

    gap = round(10 * scale)
    block_h = place_im.height + sum(s.height + gap for s in sub_ims)
    block_w = max([place_im.width] + [s.width for s in sub_ims])

    rule_w = max(2, round(4 * scale))
    pad = round(18 * scale)
    layer = Image.new("RGBA", (rule_w + pad + block_w, block_h), (0, 0, 0, 0))
    ImageDraw.Draw(layer).rectangle([0, 0, rule_w, block_h],
                                    fill=B.rgb(B.GOLD) + (255,))
    y = 0
    R.paste(layer, place_im, rule_w + pad, y)
    y += place_im.height
    for s in sub_ims:
        y += gap
        R.paste(layer, s, rule_w + pad, y)
        y += s.height

    if tone == "dark":
        layer = R.with_shadow(layer, opacity=150)

    x, y, anchor = _corner(canvas, corner)
    R.paste(im, layer, x, y, anchor=anchor)
    return im


# ==========================================================================
# 4. Music credit
# ==========================================================================
def music(canvas, track, artist=None, tone="dark"):
    """Lower-left track credit. Transient, so type and shadow, no panel."""
    fw, fh = B.CANVASES[canvas]
    im = R.frame(canvas)
    scale = fw / 1080.0
    ink = B.WHITE if tone == "dark" else B.BLACK

    kick = R.text("NOW PLAYING", round(24 * scale), B.GOLD, tracking=0.20)
    trk = R.text(track.upper(), round(46 * scale), ink, tracking=0.04)
    art = R.text(artist.upper(), round(28 * scale),
                 GREY if tone == "dark" else "#4A4A52", tracking=0.12) if artist else None

    gap = round(10 * scale)
    h = kick.height + gap + trk.height + ((gap + art.height) if art else 0)
    w = max(kick.width, trk.width, art.width if art else 0)
    layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    y = 0
    for piece in [kick, trk] + ([art] if art else []):
        R.paste(layer, piece, 0, y)
        y += piece.height + gap

    if tone == "dark":
        layer = R.with_shadow(layer, opacity=160)

    bottom = B.SAFE_ZONES_9X16["bottom"] if canvas == "9x16" else 0.09
    R.paste(im, layer, round(fw * 0.06),
            fh - round(fh * bottom) - round(fh * 0.02), anchor="lb")
    return im


# ==========================================================================
# 5. Follow bug - persistent, site only
# ==========================================================================
def follow_bug(canvas, word="FOLLOW", corner="bottom-right"):
    """A compact panel version of the lower third, for long-running footage.

    This one keeps its panel. It is on screen for minutes rather than a beat,
    and over that long it will cross every exposure in the edit; type with a
    shadow alone eventually lands on something that eats it.
    """
    fw, fh = B.CANVASES[canvas]
    im = R.frame(canvas)
    scale = fw / 1080.0

    kick = R.text(word.upper(), round(24 * scale), B.GOLD, tracking=0.20)
    site = R.text(B.WEBSITE.upper(), round(38 * scale), B.WHITE, tracking=0.06)

    bar_w = round(14 * scale)
    pad = round(22 * scale)
    gap = round(8 * scale)
    pw = bar_w + pad + max(kick.width, site.width) + pad
    ph = pad + kick.height + gap + site.height + pad

    panel = Image.new("RGBA", (pw, ph), (0, 0, 0, 214))
    ImageDraw.Draw(panel).rectangle([0, 0, bar_w, ph], fill=B.rgb(B.GOLD) + (255,))
    R.paste(panel, kick, bar_w + pad, pad)
    R.paste(panel, site, bar_w + pad, pad + kick.height + gap)

    x, y, anchor = _corner(canvas, corner)
    R.paste(im, panel, x, y, anchor=anchor)
    return im


# ==========================================================================
# Pre-generated set - only the text that does not change per video
# ==========================================================================
DEFAULT_CHAPTERS = [
    ("01", "THE PICKUP"), ("02", "WALKAROUND"), ("03", "FIRST START"),
    ("04", "THE DRIVE"),  ("05", "THE RETURN"), ("06", "THE FLEET"),
]


def build():
    n = 0
    for canvas in CANVASES:
        for tone in ("dark", "light"):
            for idx, label in DEFAULT_CHAPTERS:
                R.save(chapter(canvas, idx, label, tone),
                       OUT / "chapters" / f"chapter_{canvas}_{idx}_{_slug(label)}_{tone}.png")
                n += 1
            for slug, label, _prose, category in B.PARTNERS:
                R.save(stamp(canvas, label, category, tone=tone),
                       OUT / "stamps" / f"stamp_{canvas}_{slug}_{tone}.png")
                n += 1
        for word in ("FOLLOW", "SUBSCRIBE"):
            for corner in ("bottom-right", "bottom-left"):
                R.save(follow_bug(canvas, word, corner),
                       OUT / "follow-bugs" / f"bug_{canvas}_{_slug(word)}_{corner}.png")
                n += 1
    return n


# ==========================================================================
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("name", help="lower third for whoever is on camera")
    p.add_argument("--name", required=True)
    p.add_argument("--role")

    p = sub.add_parser("chapter", help="numbered segment marker")
    p.add_argument("--index", required=True)
    p.add_argument("--label", required=True)

    p = sub.add_parser("stamp", help="corner place-and-date")
    p.add_argument("--place", required=True)
    p.add_argument("--sub")
    p.add_argument("--date")
    p.add_argument("--corner", default="top-left",
                   choices=["top-left", "top-right", "bottom-left", "bottom-right"])

    p = sub.add_parser("music", help="track credit")
    p.add_argument("--track", required=True)
    p.add_argument("--artist")

    sub.add_parser("all", help="regenerate the fixed set")

    for p in sub.choices.values():
        if p.prog.rsplit(" ", 1)[-1] != "all":
            p.add_argument("--canvas", action="append", choices=list(CANVASES),
                           help="repeatable; default is all four")
            p.add_argument("--tone", default="dark", choices=["dark", "light"])

    a = ap.parse_args()
    if a.cmd == "all":
        print(f"{build()} files -> {OUT}")
        return

    canvases = a.canvas or list(CANVASES)
    made = []
    for c in canvases:
        if a.cmd == "name":
            im, path = name_bar(c, a.name, a.role), \
                OUT / "names" / f"name_{c}_{_slug(a.name)}.png"
        elif a.cmd == "chapter":
            im, path = chapter(c, a.index, a.label, a.tone), \
                OUT / "chapters" / f"chapter_{c}_{a.index}_{_slug(a.label)}_{a.tone}.png"
        elif a.cmd == "stamp":
            im, path = stamp(c, a.place, a.sub, a.date, a.corner, a.tone), \
                OUT / "stamps" / f"stamp_{c}_{_slug(a.place)}_{a.corner}_{a.tone}.png"
        else:
            im, path = music(c, a.track, a.artist, a.tone), \
                OUT / "music" / f"music_{c}_{_slug(a.track)}_{a.tone}.png"
        made.append(R.save(im, path))
    for m in made:
        print(m.relative_to(B.KIT))


if __name__ == "__main__":
    main()
